apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: default
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    v
    storage "postgresql" {
    connection_url="postgres://postgres:x@192.168.100.140:5432/vault-dev?sslmode=disable"
    table="vault_kv_store"
    }
