apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: x@x.x.x:x
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    x
    -----END OPENSSH PRIVATE KEY-----