---

- hosts: db_servers
  become: true
  tasks:

  - name: install vim package
    apt:
      name: vim
      state: absent
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: absent
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
